	,"gentoo/hints_hpux - Fix hpux hints"
	,"gentoo/aix_soname - aix gcc detection and shared library soname support"
	,"gentoo/EUMM-RUNPATH - https://bugs.gentoo.org/105054 cpan/ExtUtils-MakeMaker: drop $PORTAGE_TMPDIR from LD_RUN_PATH"
	,"gentoo/config_over - Remove -rpath and append LDFLAGS to lddlflags"
	,"gentoo/opensolaris_headers - Add headers for opensolaris"
	,"gentoo/patchlevel - List packaged patches for perl(#1) in patchlevel.h"
	,"gentoo/cpanplus_definstalldirs - Configure CPANPLUS to use the site directories by default."
	,"gentoo/cleanup-paths - Cleanup PATH and shrpenv"
	,"gentoo/enc2xs - Tweak enc2xs to follow symlinks and ignore missing @INC directories."
	,"gentoo/darwin-cc-ld - https://bugs.gentoo.org/297751 darwin: Use $CC to link"
	,"gentoo/cpan_definstalldirs - Provide a sensible INSTALLDIRS default for modules installed from CPAN."
	,"gentoo/interix - Fix interix hints"
	,"gentoo/create_libperl_soname - https://bugs.gentoo.org/286840 Set libperl soname"
	,"gentoo/mod_paths - Add /etc/perl to @INC"
	,"gentoo/EUMM_perllocalpod - cpan/ExtUtils-MakeMaker: remove targets that generate perllocal.pod"
	,"gentoo/drop_fstack_protector - https://bugs.gentoo.org/348557 Don't force -fstack-protector on everyone"
	,"gentoo/usr_local - Configure: Don't include sources in /usr/local/ for compiling perl"
	,"gentoo/D-SHA-CFLAGS - https://bugs.gentoo.org/506818 Do not set custom CFLAGS in cpan/Digest-SHA"
	,"gentoo/io_socket_ip_tests - cpan/IO-Socket-IP: Disable network tests"
	,"gentoo/tests - Fix EUMM podlocal tests"
	,"debian/cpan-missing-site-dirs - Fix CPAN::FirstTime defaults with nonexisting site dirs if a parent is writable"
	,"debian/makemaker-pasthru - Pass LD settings through to subdirectories"
	,"fixes/memoize_storable_nstore - [rt.cpan.org #77790] Memoize::Storable: respect 'nstore' option not respected"
	,"fixes/podman-pipe - Better errors for man pages from standard input"
	,"fixes/respect_umask - Respect umask during installation"
	,"fixes/net_smtp_docs - [rt.cpan.org #36038] Document the Net::SMTP 'Port' option"
	,"fixes/document_makemaker_ccflags - [rt.cpan.org #68613] Document that CCFLAGS should include $Config{ccflags}"
	,"fixes/parallel-manisort.patch - Fix parallel building"
